package com.quindel.quindelgenesis.application.mapper;

import com.quindel.quindelgenesis.application.dto.PriceResponseDTO;
import com.quindel.quindelgenesis.domain.model.Price;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

/**
 * Mapper class that uses MapStruct to generate the implementation of object conversion.
 */
@Mapper
public interface PriceMapper {

    /**
     * Instance generated by MapStruct.
     */
    PriceMapper INSTANCE = Mappers.getMapper(PriceMapper.class);

    /**
     * Method that converts a Price entity to a PriceResponseDTO.
     *
     * @param priceEntity a Price entity {@link Price}
     * @return A PriceResponseDTO {@link PriceResponseDTO}
     */
    @Mapping(target = "brandId", source = "brand.id")
    PriceResponseDTO mapToPriceResponseDto(Price priceEntity);

}